name: Comment CSV diff

on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    branches:
      - "*"
    paths:
      - 'data/**'
      - '.github/workflows/comment-diff.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  comment-diff:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write

    steps:
    - name: Checkout main branch into main_branch_content directory
      uses: actions/checkout@v4
      with:
        ref: main
        path: main_branch_content/

    - name: install nkf
      run: |
        sudo apt-get install -y nkf

    - name: Build CSV for main branch
      run: |
        cd main_branch_content/
        npm ci
        npm run build-csv

    - name: Checkout current branch into current_branch_content directory
      uses: actions/checkout@v4
      with:
        path: current_branch_content/

    - name: Build CSV for current branch
      run: |
        cd current_branch_content/
        npm ci
        npm run build-csv

    - name: Add comment to show CSV diff
      id: csv_diff_step
      run: ./current_branch_content/src/csvdiff.sh
      continue-on-error: true
        
    - uses: peter-evans/find-comment@v2
      id: find-comment
      if: steps.csv_diff_step.outcome == 'success'
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: '今回更新されたデータの CSV 差分は以下の通りです'

    - uses: peter-evans/create-or-update-comment@v3
      if: steps.csv_diff_step.outcome == 'success'
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: './comment.txt'
        edit-mode: 'replace'